apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bza5lf9xe-go
  janus-idp.io/tekton: bza5lf9xe-go
  backstage.io/kubernetes-id: bza5lf9xe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bza5lf9xe-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
