apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bza5lf9xe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bza5lf9xe-go 
  name: bza5lf9xe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bza5lf9xe-go 
